const words = [
    { word: "pineapple", clue: "Tropical fruit"},
    { word: "elephant", clue: "Largest land animal" },
    { word: "mountain", clue: "Large natural elevation of the earth's surface" },
    { word: "guitar", clue: "Stringed musical instrument" },
    { word: "library", clue: "Place where books are kept" },
    { word: "jupiter", clue: "Largest planet in the solar system" },
    { word: "volcano", clue: "Mountain that erupts with lava" },
    { word: "octopus", clue: "Sea creature with eight arms" },
    { word: "piano", clue: "Large keyboard musical instrument" },
    { word: "chocolate", clue: "Sweet treat made from cocoa" },
    { word: "sphinx", clue: "Mythical creature with the body of a lion and head of a human" },
    { word: "penguin", clue: "Flightless bird found in Antarctica" },
    { word: "kitchen", clue: "Room where food is prepared and cooked" },
    { word: "pyramid", clue: "Triangular structure built in ancient Egypt" },
    { word: "butterfly", clue: "Insect with colorful wings" },
    { word: "rainbow", clue: "Colorful arc in the sky after rain" },
    { word: "basketball", clue: "Sport played with an orange ball and a hoop" },
    { word: "diamond", clue: "Hard, precious gemstone" },
    { word: "safari", clue: "Adventure trip to see wild animals" },
    { word: "castle", clue: "Large fortified building from the medieval period" },
    { word: "astronaut", clue: "Person who travels in space" },
    { word: "caterpillar", clue: "Larva of a butterfly or moth" },
    { word: "sunflower", clue: "Tall plant with a large yellow flower" },
    { word: "telescope", clue: "Instrument for observing distant objects" },
    { word: "bicycle", clue: "Two-wheeled vehicle powered by pedaling" },
    { word: "sushi", clue: "Japanese dish with vinegared rice and seafood" },
    { word: "tornado", clue: "Violent rotating column of air in contact with the ground" },
    { word: "koala", clue: "Australian marsupial that lives in eucalyptus trees" },
    { word: "rainforest", clue: "Dense, tropical forest with high rainfall" },
    { word: "microscope", clue: "Instrument used to see small objects" },
    { word: "canyon", clue: "Deep gorge typically with a river flowing through it" },
    { word: "parachute", clue: "Device used to slow the descent of a person or object" },
    { word: "violin", clue: "Stringed musical instrument played with a bow" },
    { word: "carousel", clue: "Amusement ride with rotating seats, often horses" },
    { word: "avocado", clue: "Green fruit with a creamy texture and large pit" },
    { word: "helicopter", clue: "Aircraft with rotating blades" },
    { word: "igloo", clue: "Dome-shaped Eskimo house made of blocks of ice" },
    { word: "jellyfish", clue: "Marine creature with a gelatinous body and tentacles" },
    { word: "kangaroo", clue: "Australian marsupial known for hopping" },
    { word: "lighthouse", clue: "Tower with a light to guide ships" },
    { word: "meteor", clue: "Space rock that enters Earth's atmosphere" },
    { word: "notebook", clue: "Book of blank pages for writing notes" },
    { word: "origami", clue: "Japanese art of paper folding" },
    { word: "quicksand", clue: "Loose, wet sand that traps objects" },
    { word: "rhinoceros", clue: "Large mammal with one or two horns on its snout" },
    { word: "snowflake", clue: "Ice crystal that falls from the sky" },
    { word: "teapot", clue: "Container used for brewing and serving tea" },
    { word: "umbrella", clue: "Device for protection against rain or sun" },
    { word: "vampire", clue: "Mythical creature that drinks blood" },
    { word: "whale", clue: "Large marine mammal" },
    { word: "xylophone", clue: "Musical instrument with wooden bars" },
    { word: "yacht", clue: "Large, luxurious boat" },
    { word: "zeppelin", clue: "Large, rigid airship" },
    { word: "honeybee", clue: "Insect known for making honey" },
    { word: "island", clue: "Landmass surrounded by water" },
    { word: "jaguar", clue: "Large wild cat found in the Americas" },
    { word: "kiwifruit", clue: "Brown fuzzy fruit with green flesh" },
    { word: "lemur", clue: "Small primate found in Madagascar" },
    { word: "moose", clue: "Large deer with broad antlers" }
];

function getWord() {
    const index = Math.floor(Math.random() * words.length);
    return words[index];
}

export default getWord;